name: Update Codeforces Card

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  update-card:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Generate Card
        run: python profile.py

      - name: Commit and Push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add codeforces_card.svg
          git diff-index --quiet HEAD || git commit -m "Automated update of Codeforces card"
          git push
